# Generated by Django 5.2.6 on 2025-09-23 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='eigenaar',
        ),
        migrations.AddField(
            model_name='agenda',
            name='begin_tijd',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agenda',
            name='eind_tijd',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agenda',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agenda',
            name='datum',
            field=models.DateField(),
        ),
    ]
