# Generated by Django 5.2.6 on 2026-01-20 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactBericht',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voornaam', models.CharField(max_length=100)),
                ('achternaam', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefoonnummer', models.CharField(blank=True, max_length=20, null=True)),
                ('woonplaats', models.CharField(blank=True, max_length=100, null=True)),
                ('onderwerp', models.CharField(max_length=200)),
                ('bericht', models.TextField()),
                ('verzonden_op', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('beschrijving', models.TextField(blank=True)),
                ('datum', models.DateField()),
                ('begin_tijd', models.TimeField(blank=True, null=True)),
                ('eind_tijd', models.TimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actie', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HulpAanvraag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(blank=True, max_length=200)),
                ('omschrijving', models.TextField()),
                ('preferred_time', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('nieuw', 'Nieuw'), ('in_behandeling', 'In behandeling'), ('ingepland', 'Ingepland'), ('afgerond', 'Afgerond')], default='nieuw', max_length=20)),
                ('aangemaakt_op', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hulpaanvragen', to=settings.AUTH_USER_MODEL)),
                ('required_skills', models.ManyToManyField(blank=True, to='app.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('commentaar', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('hulpaanvraag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='app.hulpaanvraag')),
            ],
        ),
        migrations.CreateModel(
            name='Bericht',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boodschap', models.TextField()),
                ('verzonden_op', models.DateTimeField(auto_now_add=True)),
                ('ontvanger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ontvangen_berichten', to=settings.AUTH_USER_MODEL)),
                ('verzender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verzonden_berichten', to=settings.AUTH_USER_MODEL)),
                ('hulpaanvraag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='berichten', to='app.hulpaanvraag')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('projectleider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dienst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('beschrijving', models.TextField(blank=True)),
                ('datum', models.DateField()),
                ('begin_tijd', models.TimeField()),
                ('eind_tijd', models.TimeField()),
                ('max_personen', models.IntegerField(default=1)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_diensten', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diensten', to='app.project')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('projectleider', 'Projectleider'), ('vrijwilliger', 'Vrijwilliger'), ('hulpvrager', 'Hulpvrager')], default='hulpvrager', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('projects', models.ManyToManyField(blank=True, to='app.project')),
                ('skills', models.ManyToManyField(blank=True, to='app.skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wachtlijst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aangemeld_op', models.DateTimeField(auto_now_add=True)),
                ('dienst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wachtlijst', to='app.dienst')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Aanmelding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('waitlist', 'Waitlist')], default='pending', max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aanmeldingen', to=settings.AUTH_USER_MODEL)),
                ('dienst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aanmeldingen', to='app.dienst')),
            ],
            options={
                'unique_together': {('volunteer', 'dienst')},
            },
        ),
    ]
