# Generated by Django 6.0.3 on 2026-04-06 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='created_on',
            new_name='aangemaakt_op',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='commentaar',
            new_name='opmerking',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='score',
        ),
        migrations.AddField(
            model_name='feedback',
            name='beoordeling',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='gebruiker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='hulpaanvraag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hulpaanvraag'),
        ),
    ]
