# Generated by Django 5.2.6 on 2025-10-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_agenda_eigenaar_agenda_begin_tijd_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactBericht',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voornaam', models.CharField(max_length=100)),
                ('achternaam', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefoonnummer', models.CharField(blank=True, max_length=20, null=True)),
                ('woonplaats', models.CharField(blank=True, max_length=100, null=True)),
                ('onderwerp', models.CharField(max_length=200)),
                ('bericht', models.TextField()),
                ('verzonden_op', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
