# Generated by Django 6.0.3 on 2026-04-06 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_created_on_feedback_aangemaakt_op_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='aanmelding',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='aanmelding',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='availability',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='availability',
            name='weekday',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bericht',
            name='hulpaanvraag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hulpaanvraag'),
        ),
        migrations.AlterField(
            model_name='bericht',
            name='ontvanger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ontvangen', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bericht',
            name='verzender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verzonden', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='beoordeling',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hulpaanvraag',
            name='status',
            field=models.CharField(default='nieuw', max_length=20),
        ),
        migrations.AlterField(
            model_name='hulpaanvraag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wachtlijst',
            name='dienst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dienst'),
        ),
    ]
