# Generated by Django 6.0.3 on 2026-04-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_aanmelding_status_alter_aanmelding_volunteer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dienst',
            name='min_personen',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='dienst',
            name='max_personen',
            field=models.IntegerField(default=3),
        ),
    ]
