# Generated by Django 6.0.4 on 2026-04-09 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_dienst_min_personen_alter_dienst_max_personen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dienst',
            name='min_personen',
        ),
        migrations.AddField(
            model_name='dienst',
            name='hulpaanvraag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diensten', to='app.hulpaanvraag'),
        ),
        migrations.AlterField(
            model_name='aanmelding',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('waitlist', 'Waitlist')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='dienst',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dienst',
            name='max_personen',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='hulpaanvraag',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='app.hulpaanvraag'),
        ),
        migrations.AlterField(
            model_name='hulpaanvraag',
            name='status',
            field=models.CharField(choices=[('nieuw', 'Nieuw'), ('in_behandeling', 'In behandeling'), ('ingepland', 'Ingepland'), ('afgerond', 'Afgerond')], default='nieuw', max_length=20),
        ),
    ]
